### ISSUE TITLE
Make an icon for the app

### ISSUE THREAD

**Issue by clement-roblot** [clement-roblot/Gridfinity-Label-Generator#1]

**Comment by PigeonSoupGit** [comment]
![drawing-1](https://github.com/user-attachments/assets/9171ea6e-7908-4ec9-96ee-c4ca1b74f2a1)

**Comment by PigeonSoupGit** [comment]
![GLG](https://github.com/user-attachments/assets/c48c8d87-f91e-49d7-8b68-ccf4467a7406)
