### ISSUE TITLE
JSON file missing?

### ISSUE THREAD

**Issue by EthanHolleman** [clement-roblot/Gridfinity-Label-Generator#7]
Great program! It seems like it is possible to generate stickers manually based on what I see in the `generate.py` file but in the example command you give you reference a json file 

`python generator.py <your_file.json>`

But I don't see any json files in this repo, would you be able to provide an example template so it can be re-worked for our own stickers? 

Thanks!!

-Ethan

**Comment by clement-roblot** [comment]
Hi Ethan,

I just pushed an example JSON you can use as reference in this commit: https://github.com/clement-roblot/Gridfinity-Label-Generator/commit/26e8e1a0e8574fc13be6bfc7580329edddb6a2f9
